# sudo docker run -d -v /tmp/.X11-unix:/tmp/.X11-unix -v `pwd`:`pwd` -e DISPLAY=$DISPLAY keikun555/docker-tlatoolbox
version: "3.9"
services:
  tlatoolbox:
    build: .
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - ./specs:/root/specs
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: "host"
