# sudo docker run -d -v /tmp/.X11-unix:/tmp/.X11-unix -v `pwd`:/root/specs -e DISPLAY=$DISPLAY kimada/docker-tlatoolbox
version: "3.9"
services:
  tlatoolbox:
    container_name: tlatoolbox
    build: .
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - .:/root/specs
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: "host"
    image: kimada/tlatoolbox:1.7.1-latest
